# Generated by Django 5.2.5 on 2025-08-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='home_cars',
        ),
        migrations.AlterModelTable(
            name='firsttable',
            table='home_firsttable',
        ),
    ]
