# Generated by Django 5.2.5 on 2025-08-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cars_table_alter_firsttable_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table=None,
        ),
        migrations.AlterModelTable(
            name='firsttable',
            table=None,
        ),
    ]
