# Generated by Django 5.2.5 on 2025-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_log', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=50)),
                ('request_type', models.CharField(max_length=50)),
            ],
        ),
    ]
